### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by mahmouddaif** [sparkfish/augraphy#141]
Hello, I installed the library via pip, and I am getting the following error.

`ImportError: cannot import name 'BleedThroughAugmentation' from 'augraphy.augmentations.bleedthrough'`

Any idea why this is happening?

**Comment by kwcckw** [comment]
> Hello, I installed the library via pip, and I am getting the following error.
> 
> `ImportError: cannot import name 'BleedThroughAugmentation' from 'augraphy.augmentations.bleedthrough'`
> 
> Any idea why this is happening?

I think it is not updated yet, could you try to install it from the repo?

    !pip install git+https://github.com/sparkfish/augraphy

**Comment by mahmouddaif** [comment]
I still get the same error.

**Comment by kwcckw** [comment]
> I still get the same error.

In that case could you try my repo? I just tested it, it shouldn't facing any issue with my repo.

    !pip install git+https://github.com/kwcckw/augraphy

**Comment by proofconstruction** [comment]
@mahmouddaif You can import `BleedThrough` from `augraphy.augmentations.bleedthrough`, or you can import it from `augraphy.augmentations` since it's available in that namespace too.

You won't be able to import `BleedThroughAugmentation` because we changed the naming scheme to remove "Augmentation" from the end of all the augmentation names.

**Comment by mahmouddaif** [comment]
@proofconstruction Thank you so much, that did it.
