### ISSUE TITLE
OpenCV error in Bleedthrough

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#224]
While re-generating the ShabbyPages dataset, I encountered many `libpng` runtime errors
<img width="977" alt="Screenshot 2023-01-14 at 10 32 03 AM" src="https://user-images.githubusercontent.com/74747193/212483735-64a1a630-a49b-4802-82a9-7ab8e82acde7.png">

 and eventually my script failed with the following error:

```
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/augraphy/augmentations/bleedthrough.py", line 190, in __call__
    image_bleedthrough_foreground = self.create_bleedthrough_foreground(image)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/augraphy/augmentations/bleedthrough.py", line 170, in create_bleedthrough_
foreground
    image_bleedthrough_foreground = cv2.resize(
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function
 'resize'
```

**Comment by kwcckw** [comment]
Do you run this locally? Could you check the folder `augraphy_cache` and see all files are valid in the folder? This may due to the image is empty/not valid and we are resizing with none size.

**Comment by proofconstruction** [comment]
Fixed with [commit 4ca1d51](https://github.com/sparkfish/augraphy/commit/4ca1d51ca7083d38e1b9b1f4b9b4bd30a7e5afc7)

**Comment by erik-koynov** [comment]
Hi all,
this issue is **not** fixed! As far as I could see the issue is that the imread / imwrite operations are not thread safe. I was using it in a custom dataset with multithreaded dataloader from pytorch. I was able to reproduce the issue by putting a break on line 167 of bleedthrough.py and deleting the image. This might mean that if we use the bleedthrough in a multithreaded setting and some other thread deletes the image/ starts writing to it while the other is just trying to open it we will not be able to open the cached image. Unfortunately cv2.imread() returns None in this case and does not raise an exception. To fix the bug - check if the image_bleedthrough_foreground is None. If it is use the same image. Could I fix it myself?

**Comment by kwcckw** [comment]
> Hi all, this issue is **not** fixed! As far as I could see the issue is that the imread / imwrite operations are not thread safe. I was using it in a custom dataset with multithreaded dataloader from pytorch. I was able to reproduce the issue by putting a break on line 167 of bleedthrough.py and deleting the image. This might mean that if we use the bleedthrough in a multithreaded setting and some other thread deletes the image/ starts writing to it while the other is just trying to open it we will not be able to open the cached image. Unfortunately cv2.imread() returns None in this case and does not raise an exception. To fix the bug - check if the image_bleedthrough_foreground is None. If it is use the same image. Could I fix it myself?

Thanks, could you submit a pull request?

**Comment by jboarman** [comment]
See PR #258 for fix submitted by @erik-koynov

**Comment by kwcckw** [comment]
@erik-koynov I just merged the pull-request. Please let me know again if there's any other unexpected issue. Thanks again for submitting the pull request.
