### ISSUE TITLE
Add more paper textures

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#34]
Right now we only have two paper textures, but even just two or three more would dramatically increase the space of generated images.

We already simulate different textures by applying several filters in the paper phase, but even small differences in the texture of the base image should translate to significant differences when gamma is modified, which in turn will mean more robust data for training edge-detection models, etc.

**Comment by shaheryar1** [comment]
We may add some crumbled paper textures because this is missing in augraphy yet a very common thing to see in real life.

![juaizv0bddczhurimuxjpywud41atxg35pxvkxhpygaj6fgblfdko68ztq2p1rkw-](https://user-images.githubusercontent.com/43179913/126030362-47c836cf-f0ad-45c2-8259-e9d38877c248.jpg)
![thumb2-crumpled-paper-texture-white-crumpled-paper-background-paper-texture-white-paper-crumpled-paper](https://user-images.githubusercontent.com/43179913/126030365-a683b005-b643-4d4f-8be5-9332cf9e694f.jpg)

**Comment by jboarman** [comment]
Great idea ... Here are a few elements of what we need to balance as we address this issue:

1. large files are permanently part of git history and can bloat even local copies of the git repo cloned to everyone's machines long after the files have been "deleted"
2. images maintained in the repo need to be "[public domain](https://en.wikipedia.org/wiki/Public_domain)" images in order to avoid licensing issues
3. paper might ideally be organized into collections based on categories such as historical documents vs business papers, etc
4. we should assess existing approaches to pulling in asset-type dependencies, which is common in other libraries that, for example, make weights for pretrained models separately downloadable; perhaps something like either the `pip download` command or simply hosting various collections on external google drives are options here?

**Public Domain Images**
At least with [Bing's image search](https://help.bing.microsoft.com/#apex/18/en-us/10006/0) and [DuckDuckGo's image search](https://help.duckduckgo.com/duckduckgo-help-pages/features/image-license/), there is an option to search only for "public domain" images, so that no licenses have to be tracked for those images.

![image](https://user-images.githubusercontent.com/1108065/126044749-fe731a81-b3b0-498b-ac27-ed33a0f73109.png)

**Comment by kwcckw** [comment]
In my previous demo, i included 2 references of open source paper texture here:

1. https://www.deviantart.com/bashcorpo/gallery/164984
2. https://flickr.com/photos/designshard/3414930446

I think the next question would be how to organize those paper texture in the repo. Should we just include a text file with links to those paper textures? Or include them in each separated folder with a text file link to the source?

**Comment by proofconstruction** [comment]
We can't safely include many additional files, both because they increase the size of the repository and because they might have conflicting licenses. Determining which license an image is released under is often quite difficult; often people will post "free" images but intend these only for personal use, and don't want them affiliated with any commercial or public use.

We could probably include 2 or 3 more images of different textures that we find with a public domain search, like @jboarman suggested above. For any other textures, maybe we could make a [wiki page](https://github.com/sparkfish/augraphy/wiki) with a list of links to some good textures we find. This way the textures are available to anyone who wants them, but they aren't included in our project directly.

**Comment by jboarman** [comment]
I could see us adding a mechanism for consuming published collections from Google Drive folders by using `gdown` to pull down those community-sourced collections.  This would also be a helpful addition to scenarios like shared Google Colab notebooks where image management can be a pain.

**Comment by kwcckw** [comment]
> 
> 
> I could see us adding a mechanism for consuming published collections from Google Drive folders by using `gdown` to pull down those community-sourced collections. This would also be a helpful addition to scenarios like shared Google Colab notebooks where image management can be a pain.

Yes, this would be great since we can just use the mechanism to retrieve those paper / font in the colab notebooks, and eventually it will benefit the other user who use our repo too.

**Comment by proofconstruction** [comment]
This is now immediately solvable with the addition of `FigshareDownloader`.

We need to source some open/public license additional paper textures, as well as stamps, stains, clips, holes, etc. and upload them to the Sparkfish account's Figshare collections.

Can we start collecting these in Google Drive for now? I'd like to have a source link for all images, so we can keep track of licensing & attribution info.

**Comment by proofconstruction** [comment]
Between `FigshareDownloader` and manually downloading image files to put into `augraphy/paper_textures`, we can call this settled.
