### ISSUE TITLE
Fix DirtyRollersAugmentation

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#36]
As @kwcckw mentioned in PR #35, the `self.transform` method is missing from DirtyRollersAugmentation.

This is old functionality that was removed in [commit ea09709](https://github.com/sparkfish/augraphy/commit/ea0970932b49288b9893e728d8c4442693b825e4), but the DirtyRollersAugmentation is disabled (`p=0.0`) in the default pipeline, so this didn't come up.

We should refactor this augmentation so we can use it again.

**Comment by proofconstruction** [comment]
@kwcckw do you want to work on this?

**Comment by kwcckw** [comment]
> 
> 
> @kwcckw do you want to work on this?

Okay, i will look into this next, probably need to restructure the whole thing later, i haven't got the chance the see the current effect yet.

**Comment by kwcckw** [comment]
I rewrite the code and using different algorithm to generate the dirty roller effect now since the previous code looks messy and i'm not really know how to fix it from there.

Right now i'm taking reference from this photo:
https://h30434.www3.hp.com/t5/image/serverpage/image-id/244054i3733CED0C39E0B0D?v=v2
![image](https://user-images.githubusercontent.com/52521979/126147099-c2111637-2728-43d6-8a26-40b19ca46bff.png)

And here's the colab notebook to the demo:
https://colab.research.google.com/drive/1n7p3hwjWJlYrUf15WLsuuNO5f7zFoE4T?usp=sharing

I added feature to create stripes in horizontal , vertical or both directions, should we make this randomize too? 

Examples:

vertical
![image](https://user-images.githubusercontent.com/52521979/126147327-20033de6-e04e-4771-837b-576b4c1b40af.png)

horizontal
![image](https://user-images.githubusercontent.com/52521979/126147351-dc6b6cee-ed85-46e9-b2c1-51ec340603f6.png)

vertical + horizontal
![image](https://user-images.githubusercontent.com/52521979/126147395-522008f9-9a9a-4801-a334-8b1402c340ac.png)

Please let me know for any area of improvement.

**Comment by proofconstruction** [comment]
These look pretty good! The effect does not always happen across the entire page, however. Sometimes only part of the page is affected, or the effect appears at regular intervals down the page. Maybe we can add a periodic effect, like the one in LowInkPeriodicLines

See this for an example:

![image](https://user-images.githubusercontent.com/1108065/126197527-8e92295a-bfca-4202-a315-d41f74022186.png)

**Comment by kwcckw** [comment]
> These look pretty good! The effect does not always happen across the entire page, however. Sometimes only part of the page is affected, or the effect appears at regular intervals down the page. Maybe we can add a periodic effect, like the one in LowInkPeriodicLines
> 
> See this [image](https://forums.macrumors.com/proxy.php?image=http%3A%2F%2Fi269.photobucket.com%2Falbums%2Fjj59%2FPaulVette%2FDSCN1561.jpg%7Eoriginal&hash=e7274a8de5492a626716d504ee672e7d) for an example.

Thanks, I will try with random effect or periodic effect later and see which one is better.

**Comment by jboarman** [comment]
The examples I'm seeing in this thread, which look like what is seen from a dirty drum on a laser printer, point out that the terminology for augmentations are not always clear.

The history for this augmentation was to create an effect that reproduced what looks like dirty rollers that caused streaks to appear when using a cheap scanner that gets lots of use and little maintenance.  That cheap scanner with dirty rollers produced streaks as seen in the following zoomed-in image for any item scanned:

![image](https://user-images.githubusercontent.com/1108065/126188539-dc8aa0ef-42dd-472c-aca6-c82ea5f280c0.png)

So, the intent was sourced from the scanner side of the equation and not from the printing side.

Having reference images as we have started to do in this issue is a great way to avoid some of these miscommunications, but we might also improve our naming of augmentations to help reduce _some_ of that confusion as well.

**Comment by kwcckw** [comment]
> 
> 
> The examples I'm seeing in this thread, which look like what is seen from a dirty drum on a laser printer, point out that the terminology for augmentations are not always clear.

Okay, so we can create another dirty drum related augmentation with the current example?

> 
> The history for this augmentation was to create an effect that reproduced what looks like dirty rollers that caused streaks to appear when using a cheap scanner that gets lots of use and little maintenance. That cheap scanner with dirty rollers produced streaks as seen in the following zoomed-in image for any item scanned:
> 
> ![image](https://user-images.githubusercontent.com/1108065/126188539-dc8aa0ef-42dd-472c-aca6-c82ea5f280c0.png)
> 

Do you have more example? Or could you describe more about it? 

As i understand, it should be a span of black vertical blurred stripes, but should they be periodic ? Or span across whole image?

And is the image provided by @proofconstruction below is one of the correct example?

![image](https://user-images.githubusercontent.com/52521979/126243051-c39f71f7-e3ee-4b05-a391-0a7861b5b66b.png)

**Comment by kwcckw** [comment]
Here are several updated examples and could you guys give some opinions on which one looks more relevant to Dirty Roller?

Example 1 （wider gaps):
![image](https://user-images.githubusercontent.com/52521979/126308689-a2f34514-745d-4d7f-bc7f-bf34948a7b85.png)

Example 2 （narrower gaps):
![image](https://user-images.githubusercontent.com/52521979/126308937-9e00ea15-ed67-4159-8038-0df93857a5db.png)

Example 3 (periodic gaps):
![image](https://user-images.githubusercontent.com/52521979/126309363-0daae32f-cb05-43af-b836-84c744cda0cf.png)

Example 4 (wider black gaps)
![image](https://user-images.githubusercontent.com/52521979/126310090-de3f3e45-84f9-47f7-b518-a6eb55fbc956.png)

**Comment by jboarman** [comment]
@kwcckw Yes, I think we should create a DirtyDrum augmentation as the work you did there was really great for that purpose.  The image from @proofconstruction should be an additional reference for the dirty drum augmentation since the point he was making there was that such effects often only affect a portion of the drum and don't span the entire page in either direction of the page.

Regarding the DirtyRollers augmentation, how hard would it be to just adapt the original code?  That code was used in a real application to test and validate its use for a neural network training problem.  So, I'd be hesitant to no try to recover that if we can.

https://github.com/sparkfish/augraphy/blob/ea0970932b49288b9893e728d8c4442693b825e4/src/Augraphy/Augmentations.py#L194-L311

**Comment by kwcckw** [comment]
> Regarding the DirtyRollers augmentation, how hard would it be to just adapt the original code? That code was used in a real application to test and validate its use for a neural network training problem. So, I'd be hesitant to no try to recover that if we can.
> 

The problem is we are missing the main function  `transform` and it is used multiple times in the code. At this point, let me recheck the previous commit and see if we are able to recover anything useful.

**Comment by proofconstruction** [comment]
All of the calls to `self.transform` take an instance method (for example, `self.apply_scanline_mask` as an argument; you should be able to modify these calls to use those methods directly on the rest of the arguments to `transform`.

The original implementation of `transform` is visible in commit 18880c6 [here](https://github.com/sparkfish/augraphy/blob/18880c622e3a363df68bf05866d8e628578711d3/src/Augraphy/Augmentations.py#L37). Basically, `transform` just takes a function and some other arguments, and applies that function to those other arguments.

**Comment by kwcckw** [comment]
> 
> 
> All of the calls to `self.transform` take an instance method (for example, `self.apply_scanline_mask` as an argument; you should be able to modify these calls to use those methods directly on the rest of the arguments to `transform`.
> 
> The original implementation of `transform` is visible in commit [18880c6](https://github.com/sparkfish/augraphy/commit/18880c622e3a363df68bf05866d8e628578711d3) [here](https://github.com/sparkfish/augraphy/blob/18880c622e3a363df68bf05866d8e628578711d3/src/Augraphy/Augmentations.py#L37). Basically, `transform` just takes a function and some other arguments, and applies that function to those other arguments.

Thanks, and here's the result i get from the modified code:
![image](https://user-images.githubusercontent.com/52521979/126464888-8027bb8c-7970-41f2-b625-ff67695df0c9.png)

This should be good enough right?

**Comment by jboarman** [comment]
This is perfect.  Looks ready to create a PR!

**Comment by kwcckw** [comment]
> 
> 
> This is perfect. Looks ready to create a PR!

Great, then i will create another PR on this and DirtyRollers later.

**Comment by proofconstruction** [comment]
Merged #41
