### ISSUE TITLE
Determine sensible image size requirements

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#47]
Some of our augmentations fail when given input images that are too small.

For example, the Letterpress augmentation generates Gaussian blobs for the ink layer, which can be [up to 95 pixels in diameter](https://github.com/sparkfish/augraphy/blob/dev/src/augraphy/augmentations/lib.py#L32). When this blob is applied to the ink layer, an error is thrown by [this line](https://github.com/sparkfish/augraphy/blob/dev/src/augraphy/augmentations/lib.py#L113) or the next, if the input image is smaller than the generated blob. We try to generate a random range where the end value of the range is smaller than the starting value.

We should determine a reasonable minimum size for images, or adjust the default values of our augmentations to allow for very small images. I think it's reasonable to say that 100x100 pixels is the minimum size, but I can think of valid reasons to work on smaller ones; single-line documents, for example, or a signature.

This is part of a bigger discussion around tuning the defaults values of every augmentation, and of the default pipeline, to produce even more realistic results.

**Comment by kwcckw** [comment]
Yea, so this should be part of the test code, and we need at least some minimal level of error prevention code since it's not quite reasonable to limit the image size. Those error prevention code should be varied to each augmentation and some general error prevention checks included zero division, overflow checking, image channels (gray/colour), types conversion and etc.

**Comment by proofconstruction** [comment]
This should be fixed by [this commit](https://github.com/sparkfish/augraphy/commit/f7454636f27735fe0bb2bbf0795a8ed8fdd49914).
